### ISSUE TITLE
Issue in running it locally

### ISSUE THREAD

**Issue by rameshbar** [UltimateSoftware/AGENT#9]
I was trying to run it locally with your sample app by following the steps in readme.. It doesn't explore the AUT.. it launches the app and closes it very next second.. did i miss something

**Comment by dionny** [comment]
Hi Ramesh.  Can you provide more information?  Are there any stack traces visible on the console when the system is running?

**Comment by rameshbar** [comment]
Ho Dionny, thanks for looking in to it.

**I noticed below errors in log (before i started agent)**

page-analyzer_1      | FileNotFoundError: [Errno 2] File b'/app/src/data/label_candidates_sys.csv' does not exist: b'/app/src/data/label_candidates_sys.csv'
 [2019-08-17 17:23:57 +0000] [1887] [INFO] Worker exiting (pid: 1887)
page-analyzer_1      | [2019-08-17 17:23:57 +0000] [1876] [ERROR] Exception in worker process
page-analyzer_1      | Traceback (most recent call last):
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
page-analyzer_1      |     worker.init_process()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
page-analyzer_1      |     self.load_wsgi()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
page-analyzer_1      |     self.wsgi = self.app.wsgi()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
page-analyzer_1      |     self.callable = self.load()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
page-analyzer_1      |     return self.load_wsgiapp()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
page-analyzer_1      |     return util.import_app(self.app_uri)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
page-analyzer_1      |     __import__(module)
page-analyzer_1      |   File "/app/src/main.py", line 15, in <module>
page-analyzer_1      |     PageAnalysisController(app).add_routes()
page-analyzer_1      |   File "/app/src/controllers/page_analysis_controller.py", line 27, in __init__
page-analyzer_1      |     self._service = PageAnalysisService()
page-analyzer_1      |   File "/app/src/services/page_analysis_service.py", line 86, in __init__
page-analyzer_1      |     self._load_classifiers()
page-analyzer_1      |   File "/app/src/services/page_analysis_service.py", line 92, in _load_classifiers
page-analyzer_1      |     self.__label_classifier_df = pd.read_csv(f'{self.base_path}/label_candidates_sys.csv')
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 697, in parser_f
page-analyzer_1      |     return _read(filepath_or_buffer, kwds)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 424, in _read
page-analyzer_1      |     parser = TextFileReader(filepath_or_buffer, **kwds)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 890, in __init__
page-analyzer_1      |     self._make_engine(self.engine)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1117, in _make_engine
page-analyzer_1      |     self._engine = CParserWrapper(self.f, **self.options)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1848, in __init__
page-analyzer_1      |     self._reader = parsers.TextReader(src, **kwds)
page-analyzer_1      |   File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
page-analyzer_1      |   File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
page-analyzer_1      | FileNotFoundError: [Errno 2] File b'/app/src/data/label_candidates_sys.csv' does not exist: b'/app/src/data/label_candidates_sys.csv'
page-analyzer_1      | [2019-08-17 17:23:57 +0000] [1876] [INFO] Worker exiting (pid: 1876)
page-analyzer_1      | [2019-08-17 17:23:57 +0000] [1860] [ERROR] Exception in worker process
page-analyzer_1      | Traceback (most recent call last):
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
page-analyzer_1      |     worker.init_process()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
page-analyzer_1      |     self.load_wsgi()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
page-analyzer_1      |     self.wsgi = self.app.wsgi()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
page-analyzer_1      |     self.callable = self.load()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
page-analyzer_1      |     return self.load_wsgiapp()
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
page-analyzer_1      |     return util.import_app(self.app_uri)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
page-analyzer_1      |     __import__(module)
page-analyzer_1      |   File "/app/src/main.py", line 15, in <module>
page-analyzer_1      |     PageAnalysisController(app).add_routes()
page-analyzer_1      |   File "/app/src/controllers/page_analysis_controller.py", line 27, in __init__
page-analyzer_1      |     self._service = PageAnalysisService()
page-analyzer_1      |   File "/app/src/services/page_analysis_service.py", line 86, in __init__
page-analyzer_1      |     self._load_classifiers()
page-analyzer_1      |   File "/app/src/services/page_analysis_service.py", line 92, in _load_classifiers
page-analyzer_1      |     self.__label_classifier_df = pd.read_csv(f'{self.base_path}/label_candidates_sys.csv')
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 697, in parser_f
page-analyzer_1      |     return _read(filepath_or_buffer, kwds)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 424, in _read
page-analyzer_1      |     parser = TextFileReader(filepath_or_buffer, **kwds)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 890, in __init__
page-analyzer_1      |     self._make_engine(self.engine)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1117, in _make_engine
page-analyzer_1      |     self._engine = CParserWrapper(self.f, **self.options)
page-analyzer_1      |   File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1848, in __init__
page-analyzer_1      |     self._reader = parsers.TextReader(src, **kwds)
page-analyzer_1      |   File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
page-analyzer_1      |   File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source


**After i started the agent, noticed below in log:**

Attaching to autonomousagent_exp-test-agent_1, autonomousagent_flower_1, autonomousagent_coordinator-agent_1, autonomousagent_seeding_1, autonomousagent_form-expert_1, autonomousagent_page-analyzer_1, autonomousagent_gateway_1, autonomousagent_mongo_1, autonomousagent_pet-clinic_1, autonomousagent_rabbitmq_1, autonomousagent_aeon-runner_1, autonomousagent_flow-generator_1
mongo_1              | WARNING: no logs are available with the 'none' log driver
pet-clinic_1         | WARNING: no logs are available with the 'none' log driver
rabbitmq_1           | WARNING: no logs are available with the 'none' log driver
exp-test-agent_1     | 2019-08-17 17:23:07,095 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
exp-test-agent_1     | 2019-08-17 17:23:07,096 INFO supervisord started with pid 1
exp-test-agent_1     | 2019-08-17 17:23:08,099 INFO spawned: 'agent' with pid 7
exp-test-agent_1     | 2019-08-17 17:23:08,439 - agent-explore-and-test - INFO - Starting agent...
exp-test-agent_1     | 2019-08-17 17:23:08,887 - agent-explore-and-test - INFO - Celery started.
exp-test-agent_1     | 2019-08-17 17:23:08,887 - agent-explore-and-test - INFO - Agent started.
exp-test-agent_1     | 2019-08-17 17:23:09,889 INFO success: agent entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
exp-test-agent_1     | 2019-08-17 17:28:27,512 - inbound-tasks - INFO - Starting session.
exp-test-agent_1     | 2019-08-17 17:28:27,561 - runner-client - INFO - Launching runner: http://aeon-runner:8080 to http://pet-clinic:8080
exp-test-agent_1     | 2019-08-17 17:28:30,243 - runner-client - INFO - Successfully launched runner.
exp-test-agent_1     | 2019-08-17 17:28:32,187 - runner-client - INFO - Successfully navigated runner.
exp-test-agent_1     | 2019-08-17 17:28:32,189 - agent-loop - INFO - Starting loop iteration 0.
exp-test-agent_1     | 2019-08-17 17:28:32,781 - runner-client - INFO - Checking for DOM ready state...
exp-test-agent_1     | 2019-08-17 17:28:33,184 - page-analysis-client - INFO - Running page analysis: http://page-analyzer:9000/v1/pageAnalysis/state/concrete
exp-test-agent_1     | 2019-08-17 17:28:33,227 - agent-loop - ERROR - Fatal error during iteration 0.
exp-test-agent_1     | Traceback (most recent call last):
exp-test-agent_1     |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
exp-test-agent_1     |     chunked=chunked)
exp-test-agent_1     |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
exp-test-agent_1     |     six.raise_from(e, None)
exp-test-agent_1     |   File "<string>", line 2, in raise_from
exp-test-agent_1     |   File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
exp-test-agent_1     |     httplib_response = conn.getresponse()
exp-test-agent_1     |   File "/usr/local/lib/python3.7/http/client.py", line 1321, in getresponse
exp-test-agent_1     |     response.begin()
exp-test-agent_1     |   File "/usr/local/lib/python3.7/http/client.py", line 296, in begin
exp-test-agent_1     |     version, status, reason = self._read_status()
exp-test-agent_1     |   File "/usr/local/lib/python3.7/http/client.py", line 257, in _read_status
exp-test-agent_1     |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
exp-test-agent_1     |   File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
exp-test-agent_1     |     return self._sock.recv_into(b)
exp-test-agent_1     | ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by rameshbar** [comment]
Hello  Dionny,

Thanks for the response. I have uploaded the error log with github issue.

Please let me know if you need more information. If required, I can do
web-sharing with you.

Thanks,
Ramesh.

**Comment by rameshbar** [comment]
Hello  Dionny,

Thanks for the response. I have uploaded the error log with github issue.

Please let me know if you need more information.

Thanks,
Ramesh.

**Comment by jozdavab** [comment]
Hi, I have the same issue as Ramesh stated in the first comment.
Is there a known fix for the problem? 
What could be the underlying cause?

David

**Comment by rameshbar** [comment]
> Hi, I have the same issue as Ramesh stated in the first comment.
> Is there a known fix for the problem?
> What could be the underlying cause?
> 
> David

David,
It got fixed after i upgraded my docker for windows version. try that please.
Thanks.

**Comment by jozdavab** [comment]
I upgraded my docker to 2.1.0.5, but the issue still remains.
Any other idea?
Could you ell me which exact version do you use?
